"""Pydantic data models for the profile engine."""

from .attribution import AttributionResult, CandidateMatch
from .content import (
    GeneratedContent,
    SourceRef,
)
from .corpus import (
    Chunk,
    Corpus,
    Document,
    DocumentFormat,
    DocumentMetadata,
    ProcessedCorpus,
)
from .features import (
    AudienceProfile,
    Marker,
    MarkerSet,
    SentenceLengthStats,
    StructuralPatterns,
    StylometricFeatures,
    VocabularyProfile,
    VocabularyRichness,
)
from .hierarchy import (
    DepartmentProfile,
    HierarchyDiff,
    OfficialPosition,
    OrganizationProfile,
    OverrideSet,
    ProfileDiff,
    ProfileHierarchy,
    ProhibitedFraming,
    RegisterInfo,
    StyleGuide,
    StylometricBaseline,
    VoiceDefinition,
)
from .monitoring import (
    Alert,
    DailyRollup,
    DriftConfig,
    DriftDiagnosis,
    DriftedFeature,
    DriftSignal,
    MonitoringJob,
    MonitoringResult,
    RepairAction,
    RepairVerification,
    Severity,
    SeverityRule,
    TrendData,
    WeeklyRollup,
)
from .profile import (
    AntiPatterns,
    ArgumentationProfile,
    AuthorIdentity,
    AuthorProfile,
    CitationProfile,
    CompositeVoiceConfig,
    ContentAccessLevel,
    EdgeCase,
    ExampleOutputs,
    ExpertiseDomains,
    Position,
    ValidationCriteria,
    VoiceAccessLevel,
    VoiceContext,
    VoiceProfile,
)
from .verification import (
    DeepResult,
    FidelityScore,
    InlineResult,
    VerificationResult,
)

__all__ = [
    # Corpus
    "Chunk",
    "Corpus",
    "Document",
    "DocumentFormat",
    "DocumentMetadata",
    "ProcessedCorpus",
    # Features
    "AudienceProfile",
    "Marker",
    "MarkerSet",
    "SentenceLengthStats",
    "StructuralPatterns",
    "StylometricFeatures",
    "VocabularyProfile",
    "VocabularyRichness",
    # Profile
    "AntiPatterns",
    "ArgumentationProfile",
    "AuthorIdentity",
    "AuthorProfile",
    "CitationProfile",
    "CompositeVoiceConfig",
    "ContentAccessLevel",
    "EdgeCase",
    "ExampleOutputs",
    "ExpertiseDomains",
    "Position",
    "ValidationCriteria",
    "VoiceAccessLevel",
    "VoiceContext",
    "VoiceProfile",
    # Hierarchy
    "DepartmentProfile",
    "HierarchyDiff",
    "OfficialPosition",
    "OrganizationProfile",
    "OverrideSet",
    "ProfileDiff",
    "ProfileHierarchy",
    "ProhibitedFraming",
    "RegisterInfo",
    "StyleGuide",
    "StylometricBaseline",
    "VoiceDefinition",
    # Content
    "GeneratedContent",
    "SourceRef",
    # Verification
    "DeepResult",
    "FidelityScore",
    "InlineResult",
    "VerificationResult",
    # Attribution
    "AttributionResult",
    "CandidateMatch",
    # Monitoring
    "Alert",
    "DailyRollup",
    "DriftConfig",
    "DriftDiagnosis",
    "DriftedFeature",
    "DriftSignal",
    "MonitoringJob",
    "MonitoringResult",
    "RepairAction",
    "RepairVerification",
    "Severity",
    "SeverityRule",
    "TrendData",
    "WeeklyRollup",
]
